"""create professional roles skills experiences join applications and application skills

Revision ID: 2abf1c27f9d9
Revises: f3785c6c18b5
Create Date: 2026-09-25 15:31:53.160232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2abf1c27f9d9'
down_revision: Union[str, Sequence[str], None] = 'f3785c6c18b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_experiences_id'), 'experiences', ['id'], unique=False)
    op.create_table('professional_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_professional_roles_id'), 'professional_roles', ['id'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_table('join_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('professional_role_id', sa.Integer(), nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.Column('github', sa.String(length=500), nullable=True),
    sa.Column('portfolio', sa.String(length=500), nullable=True),
    sa.Column('linkedin', sa.String(length=500), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('terms', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ),
    sa.ForeignKeyConstraint(['professional_role_id'], ['professional_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_join_applications_email'), 'join_applications', ['email'], unique=False)
    op.create_index(op.f('ix_join_applications_experience_id'), 'join_applications', ['experience_id'], unique=False)
    op.create_index(op.f('ix_join_applications_id'), 'join_applications', ['id'], unique=False)
    op.create_index(op.f('ix_join_applications_professional_role_id'), 'join_applications', ['professional_role_id'], unique=False)
    op.create_table('application_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['join_applications.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_skills_application_id'), 'application_skills', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_skills_id'), 'application_skills', ['id'], unique=False)
    op.create_index(op.f('ix_application_skills_skill_id'), 'application_skills', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_skills_skill_id'), table_name='application_skills')
    op.drop_index(op.f('ix_application_skills_id'), table_name='application_skills')
    op.drop_index(op.f('ix_application_skills_application_id'), table_name='application_skills')
    op.drop_table('application_skills')
    op.drop_index(op.f('ix_join_applications_professional_role_id'), table_name='join_applications')
    op.drop_index(op.f('ix_join_applications_id'), table_name='join_applications')
    op.drop_index(op.f('ix_join_applications_experience_id'), table_name='join_applications')
    op.drop_index(op.f('ix_join_applications_email'), table_name='join_applications')
    op.drop_table('join_applications')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_professional_roles_id'), table_name='professional_roles')
    op.drop_table('professional_roles')
    op.drop_index(op.f('ix_experiences_id'), table_name='experiences')
    op.drop_table('experiences')
    # ### end Alembic commands ###
