"""initial schema

Revision ID: 4eb22033a273
Revises: 
Create Date: 2026-10-04 14:52:34.979011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb22033a273'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estimated_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estimated_budgets_id'), 'estimated_budgets', ['id'], unique=False)
    op.create_index(op.f('ix_estimated_budgets_name'), 'estimated_budgets', ['name'], unique=True)
    op.create_table('expected_timelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expected_timelines_id'), 'expected_timelines', ['id'], unique=False)
    op.create_index(op.f('ix_expected_timelines_name'), 'expected_timelines', ['name'], unique=True)
    op.create_table('experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_experiences_id'), 'experiences', ['id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('professional_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_professional_roles_id'), 'professional_roles', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('service_requireds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_requireds_id'), 'service_requireds', ['id'], unique=False)
    op.create_index(op.f('ix_service_requireds_name'), 'service_requireds', ['name'], unique=True)
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_table('join_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('professional_role_id', sa.Integer(), nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.Column('github', sa.String(length=500), nullable=True),
    sa.Column('portfolio', sa.String(length=500), nullable=True),
    sa.Column('linkedin', sa.String(length=500), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('terms', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ),
    sa.ForeignKeyConstraint(['professional_role_id'], ['professional_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_join_applications_email'), 'join_applications', ['email'], unique=False)
    op.create_index(op.f('ix_join_applications_experience_id'), 'join_applications', ['experience_id'], unique=False)
    op.create_index(op.f('ix_join_applications_id'), 'join_applications', ['id'], unique=False)
    op.create_index(op.f('ix_join_applications_professional_role_id'), 'join_applications', ['professional_role_id'], unique=False)
    op.create_index(op.f('ix_join_applications_status'), 'join_applications', ['status'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('service_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('company', sa.String(length=150), nullable=True),
    sa.Column('service_required_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=True),
    sa.Column('timeline_id', sa.Integer(), nullable=True),
    sa.Column('additional_information', sa.Text(), nullable=True),
    sa.Column('terms', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['estimated_budgets.id'], ),
    sa.ForeignKeyConstraint(['service_required_id'], ['service_requireds.id'], ),
    sa.ForeignKeyConstraint(['timeline_id'], ['expected_timelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_requests_budget_id'), 'service_requests', ['budget_id'], unique=False)
    op.create_index(op.f('ix_service_requests_email'), 'service_requests', ['email'], unique=False)
    op.create_index(op.f('ix_service_requests_id'), 'service_requests', ['id'], unique=False)
    op.create_index(op.f('ix_service_requests_service_required_id'), 'service_requests', ['service_required_id'], unique=False)
    op.create_index(op.f('ix_service_requests_status'), 'service_requests', ['status'], unique=False)
    op.create_index(op.f('ix_service_requests_timeline_id'), 'service_requests', ['timeline_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('application_skills',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['join_applications.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('application_id', 'skill_id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=30), server_default='', nullable=True),
    sa.Column('profile_image', sa.String(length=500), server_default='', nullable=True),
    sa.Column('bio', sa.Text(), server_default='', nullable=True),
    sa.Column('address', sa.String(length=255), server_default='', nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_table('application_skills')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_service_requests_timeline_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_status'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_service_required_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_email'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_budget_id'), table_name='service_requests')
    op.drop_table('service_requests')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_join_applications_status'), table_name='join_applications')
    op.drop_index(op.f('ix_join_applications_professional_role_id'), table_name='join_applications')
    op.drop_index(op.f('ix_join_applications_id'), table_name='join_applications')
    op.drop_index(op.f('ix_join_applications_experience_id'), table_name='join_applications')
    op.drop_index(op.f('ix_join_applications_email'), table_name='join_applications')
    op.drop_table('join_applications')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_service_requireds_name'), table_name='service_requireds')
    op.drop_index(op.f('ix_service_requireds_id'), table_name='service_requireds')
    op.drop_table('service_requireds')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_professional_roles_id'), table_name='professional_roles')
    op.drop_table('professional_roles')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_experiences_id'), table_name='experiences')
    op.drop_table('experiences')
    op.drop_index(op.f('ix_expected_timelines_name'), table_name='expected_timelines')
    op.drop_index(op.f('ix_expected_timelines_id'), table_name='expected_timelines')
    op.drop_table('expected_timelines')
    op.drop_index(op.f('ix_estimated_budgets_name'), table_name='estimated_budgets')
    op.drop_index(op.f('ix_estimated_budgets_id'), table_name='estimated_budgets')
    op.drop_table('estimated_budgets')
    # ### end Alembic commands ###
