"""create service request lookup tables

Revision ID: 8c8506756181
Revises: 2abf1c27f9d9
Create Date: 2026-09-26 13:37:16.488428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c8506756181'
down_revision: Union[str, Sequence[str], None] = '2abf1c27f9d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estimated_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estimated_budgets_id'), 'estimated_budgets', ['id'], unique=False)
    op.create_index(op.f('ix_estimated_budgets_name'), 'estimated_budgets', ['name'], unique=True)
    op.create_table('expected_timelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expected_timelines_id'), 'expected_timelines', ['id'], unique=False)
    op.create_index(op.f('ix_expected_timelines_name'), 'expected_timelines', ['name'], unique=True)
    op.create_table('service_requireds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_requireds_id'), 'service_requireds', ['id'], unique=False)
    op.create_index(op.f('ix_service_requireds_name'), 'service_requireds', ['name'], unique=True)
    op.create_table('service_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('company', sa.String(length=150), nullable=True),
    sa.Column('service_required_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=True),
    sa.Column('timeline_id', sa.Integer(), nullable=True),
    sa.Column('additional_information', sa.Text(), nullable=True),
    sa.Column('terms', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['estimated_budgets.id'], ),
    sa.ForeignKeyConstraint(['service_required_id'], ['service_requireds.id'], ),
    sa.ForeignKeyConstraint(['timeline_id'], ['expected_timelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_requests_budget_id'), 'service_requests', ['budget_id'], unique=False)
    op.create_index(op.f('ix_service_requests_email'), 'service_requests', ['email'], unique=False)
    op.create_index(op.f('ix_service_requests_id'), 'service_requests', ['id'], unique=False)
    op.create_index(op.f('ix_service_requests_service_required_id'), 'service_requests', ['service_required_id'], unique=False)
    op.create_index(op.f('ix_service_requests_status'), 'service_requests', ['status'], unique=False)
    op.create_index(op.f('ix_service_requests_timeline_id'), 'service_requests', ['timeline_id'], unique=False)
    op.drop_index(op.f('ix_application_skills_application_id'), table_name='application_skills')
    op.drop_index(op.f('ix_application_skills_id'), table_name='application_skills')
    op.drop_index(op.f('ix_application_skills_skill_id'), table_name='application_skills')
    op.drop_column('application_skills', 'id')
    op.alter_column('experiences', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('professional_roles', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('skills', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skills', 'name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('professional_roles', 'name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('experiences', 'name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.add_column('application_skills', sa.Column('id', sa.INTEGER(), nullable=False))
    op.create_index(op.f('ix_application_skills_skill_id'), 'application_skills', ['skill_id'], unique=False)
    op.create_index(op.f('ix_application_skills_id'), 'application_skills', ['id'], unique=False)
    op.create_index(op.f('ix_application_skills_application_id'), 'application_skills', ['application_id'], unique=False)
    op.drop_index(op.f('ix_service_requests_timeline_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_status'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_service_required_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_email'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_budget_id'), table_name='service_requests')
    op.drop_table('service_requests')
    op.drop_index(op.f('ix_service_requireds_name'), table_name='service_requireds')
    op.drop_index(op.f('ix_service_requireds_id'), table_name='service_requireds')
    op.drop_table('service_requireds')
    op.drop_index(op.f('ix_expected_timelines_name'), table_name='expected_timelines')
    op.drop_index(op.f('ix_expected_timelines_id'), table_name='expected_timelines')
    op.drop_table('expected_timelines')
    op.drop_index(op.f('ix_estimated_budgets_name'), table_name='estimated_budgets')
    op.drop_index(op.f('ix_estimated_budgets_id'), table_name='estimated_budgets')
    op.drop_table('estimated_budgets')
    # ### end Alembic commands ###
