"""add first and last name to users

Revision ID: f3785c6c18b5
Revises: eb2887cf4d01
Create Date: 2026-09-19 14:48:19.009023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3785c6c18b5'
down_revision: Union[str, Sequence[str], None] = 'eb2887cf4d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'first_name')
    op.drop_column('profiles', 'last_name')
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.add_column('profiles', sa.Column('last_name', sa.VARCHAR(length=100), nullable=True))
    op.add_column('profiles', sa.Column('first_name', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
